### ISSUE TITLE
I get the error when trying to run a benchmark on the homepage

### ISSUE THREAD

**Issue by capaj** [gpujs/gpu.js#150]
I am on ubuntu 17.04, chrome Version 59.0.3071.115 (Official Build) (64-bit) and I've got Radeon RX480 gpu.

My stack:
```
"TypeError: Cannot read property '0' of undefined
    at u.fn (eval at value (http://gpu.rocks/js/gpu.min.js?1aebp6M9Sq:15:7986), <anonymous>:11:54)
    at u.eval (eval at value (http://gpu.rocks/js/gpu.min.js?1aebp6M9Sq:15:7986), <anonymous>:25:62)
    at u.<anonymous> (http://gpu.rocks/js/gpu.min.js?1aebp6M9Sq:15:6774)
    at Object.u [as cpu] (http://gpu.rocks/js/gpu.min.js?1aebp6M9Sq:15:22158)
    at Benchmark.<anonymous> (http://gpu.rocks/js/demo.js?A8c4dQ5ZsP:65:29)
    at Benchmark.uid1500640339517createFunction (<anonymous>:3:128)
    at clock (http://gpu.rocks/js/benchmark.js:1628:22)
    at clock (http://gpu.rocks/js/benchmark.js:1802:20)
    at cycle (http://gpu.rocks/js/benchmark.js:1991:49)
    at Benchmark.run (http://gpu.rocks/js/benchmark.js:2098:13)"
```

```
{
  "timeStamp": 1500640246653,
  "type": "error",
  "target": {
    "name": "multiplyMatrix.cpu",
    "options": {
      "async": false,
      "defer": false,
      "delay": 0.005,
      "initCount": 1,
      "maxTime": 5,
      "minSamples": 5,
      "minTime": 0.075
    },
    "async": false,
    "defer": false,
    "delay": 0.005,
    "initCount": 1,
    "maxTime": 5,
    "minSamples": 5,
    "minTime": 0.075,
    "id": 1,
    "stats": {
      "moe": 0,
      "rme": 0,
      "sem": 0,
      "deviation": 0,
      "mean": 0,
      "sample": [],
      "variance": 0
    },
    "times": {
      "cycle": 0,
      "elapsed": 0,
      "period": 0,
      "timeStamp": 0
    },
    "events": {
      "complete": []
    },
    "running": false,
    "count": 0,
    "cycles": 0,
    "error": {},
    "aborted": true
  },
  "currentTarget": {
    "0": {
      "name": "multiplyMatrix.cpu",
      "options": {
        "async": false,
        "defer": false,
        "delay": 0.005,
        "initCount": 1,
        "maxTime": 5,
        "minSamples": 5,
        "minTime": 0.075
      },
      "async": false,
      "defer": false,
      "delay": 0.005,
      "initCount": 1,
      "maxTime": 5,
      "minSamples": 5,
      "minTime": 0.075,
      "id": 1,
      "stats": {
        "moe": 0,
        "rme": 0,
        "sem": 0,
        "deviation": 0,
        "mean": 0,
        "sample": [],
        "variance": 0
      },
      "times": {
        "cycle": 0,
        "elapsed": 0,
        "period": 0,
        "timeStamp": 0
      },
      "events": {
        "complete": []
      },
      "running": false,
      "count": 0,
      "cycles": 0,
      "error": {},
      "aborted": true
    },
    "1": {
      "name": "multiplyMatrix.gpu",
      "options": {
        "async": false,
        "defer": false,
        "delay": 0.005,
        "initCount": 1,
        "maxTime": 5,
        "minSamples": 5,
        "minTime": 0.075
      },
      "async": false,
      "defer": false,
      "delay": 0.005,
      "initCount": 1,
      "maxTime": 5,
      "minSamples": 5,
      "minTime": 0.075,
      "id": 2,
      "stats": {
        "moe": 0.00000550371788247589,
        "rme": 3.5506685901283546,
        "sem": 0.0000026536730388022617,
        "deviation": 0.000012726568812052943,
        "mean": 0.00015500511362219065,
        "sample": [
          0.00018760757314974184,
          0.00015088927137119908,
          0.00015375788869764775,
          0.00015605278255880666,
          0.00016351118760757314,
          0.00014859437751004018,
          0.00014113597246127367,
          0.00014802065404475044,
          0.0001629374641422834,
          0.00015261044176706828,
          0.00015777395295467586,
          0.00015318416523235802,
          0.00015949512335054506,
          0.00015777395295467586,
          0.0001583476764199656,
          0.00015375788869764775,
          0.00015892139988525533,
          0.00016064257028112453,
          0.00015375788869764775,
          0.00011130235226620769,
          0.00015605278255880666,
          0.00016121629374641423,
          0.00015777395295467586
        ],
        "variance": 1.6196555372791865e-10
      },
      "times": {
        "cycle": 0.2701739130434783,
        "elapsed": 6.947,
        "period": 0.00015500511362219065,
        "timeStamp": 1500640246660
      },
      "_timerId": 34,
      "events": {
        "complete": []
      },
      "running": false,
      "count": 1743,
      "cycles": 3,
      "hz": 6451.400064370775
    },
    "options": {},
    "length": 2,
    "events": {
      "complete": [
        null
      ],
      "error": [
        null
      ]
    },
    "running": false
  }
}```

**Comment by daflair** [comment]
I am also getting "There was an error running on the GPU." with the latest site update, a couple of days ago there were no issues running the benchmarks...

**Hardware:**
MacBook Pro (15-inch, 2016) 2.6 GHz Intel Core i7, 16 GB 2133 MHz LPDDR3
Radeon Pro 450 2048 MB, Intel HD Graphics 530 1536 MB
*System Report for Active GPU:*
```
Radeon Pro 450:

  Chipset Model:	AMD Radeon Pro 450
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Total):	2048 MB
  Vendor:	ATI (0x1002)
  Device ID:	0x67ef
  Revision ID:	0x00ef
  ROM Revision:	113-C980AF-908
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.29 [3.2.8]
  EFI Driver Version:	01.00.908
  Metal:	Supported
  Displays:
Color LCD:
  Display Type:	Built-In Retina LCD
  Resolution:	2880 x 1800 Retina
  Pixel Depth:	32-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
  Connection Type:	DisplayPort
LG Ultra HD:
  Resolution:	2560 x 1440 @ 60 Hz
  Pixel Depth:	30-Bit Color (ARGB2101010)
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
  Connection Type:	DVI or HDMI
  Adapter Firmware Version:	7.26
```

**OS:**
macOS Sierra 10.12.5 (16F73)

**Browsers:**
* Safari Version 10.1.1 (12603.2.4)
* Safari Technology Preview Release 35 (Safari 11.0, WebKit 12604.1.29)
* Chrome Version 60.0.3112.72 (Official Build) beta (64-bit)
* Chrome Version 61.0.3163.0 (Official Build) canary (64-bit)
* Electron Version 1.7.5 (1.7.5)

**Log:**
```
09:06:31.164 demo.js?A8c4dQ5ZsP:101 Event {timeStamp: 1500642391164, type: "error", target: Benchmark, currentTarget: Suite(2)}currentTarget: Suite(2)0: Benchmark {name: "multiplyMatrix.cpu", options: {…}, async: false, defer: false, delay: 0.005, …}1: Benchmark {name: "multiplyMatrix.gpu", options: {…}, async: false, defer: false, delay: 0.005, …}events: {complete: Array(1), error: Array(1)}length: 2name: undefinedoptions: {name: undefined}running: true__proto__: Object(0)result: undefinedtarget: Benchmarkaborted: trueasync: falsecompiled: ƒ function(window,t15006423889660)count: 0cycles: 0defer: falsedelay: 0.005error: TypeError: Cannot read property '0' of undefined
    at u.fn (eval at value (http://gpu.rocks/js/gpu.min.js?1aebp6M9Sq:15:7986), <anonymous>:11:54)
    at u.eval (eval at value (http://gpu.rocks/js/gpu.min.js?1aebp6M9Sq:15:7986), <anonymous>:25:62)
    at u.<anonymous> (http://gpu.rocks/js/gpu.min.js?1aebp6M9Sq:15:6774)
    at Object.u [as cpu] (http://gpu.rocks/js/gpu.min.js?1aebp6M9Sq:15:22158)
    at Benchmark.<anonymous> (http://gpu.rocks/js/demo.js?A8c4dQ5ZsP:65:29)
    at Benchmark.uid1500642388966createFunction (<anonymous>:3:128)
    at clock (http://gpu.rocks/js/benchmark.js:1628:22)
    at clock (http://gpu.rocks/js/benchmark.js:1802:20)
    at cycle (http://gpu.rocks/js/benchmark.js:1991:49)
    at Benchmark.run (http://gpu.rocks/js/benchmark.js:2098:13)message: "Cannot read property '0' of undefined"stack: "TypeError: Cannot read property '0' of undefined↵    at u.fn (eval at value (http://gpu.rocks/js/gpu.min.js?1aebp6M9Sq:15:7986), <anonymous>:11:54)↵    at u.eval (eval at value (http://gpu.rocks/js/gpu.min.js?1aebp6M9Sq:15:7986), <anonymous>:25:62)↵    at u.<anonymous> (http://gpu.rocks/js/gpu.min.js?1aebp6M9Sq:15:6774)↵    at Object.u [as cpu] (http://gpu.rocks/js/gpu.min.js?1aebp6M9Sq:15:22158)↵    at Benchmark.<anonymous> (http://gpu.rocks/js/demo.js?A8c4dQ5ZsP:65:29)↵    at Benchmark.uid1500642388966createFunction (<anonymous>:3:128)↵    at clock (http://gpu.rocks/js/benchmark.js:1628:22)↵    at clock (http://gpu.rocks/js/benchmark.js:1802:20)↵    at cycle (http://gpu.rocks/js/benchmark.js:1991:49)↵    at Benchmark.run (http://gpu.rocks/js/benchmark.js:2098:13)"__proto__: Errorevents: {complete: Array(0)}f15006423889661: ƒ function()fn: ƒ function()id: 1initCount: 1maxTime: 5minSamples: 5minTime: 0.075name: "multiplyMatrix.cpu"options: {async: false, defer: false, delay: 0.005, id: undefined, initCount: 1, …}running: falsestats: {moe: 0, rme: 0, sem: 0, deviation: 0, mean: 0, …}times: {cycle: 0, elapsed: 0, period: 0, timeStamp: 0}__proto__: ObjecttimeStamp: 1500642391164type: "error"__proto__: Object
09:06:42.798 demo.js?A8c4dQ5ZsP:80 Object
```

**Comment by fuzzie360** [comment]
Thanks for the quick report guys! I'm able to reproduce

**Comment by daflair** [comment]
I did some debugging and it seems that in demo.js:15 `var matrixSize = 1` is used to create the matrices `a` and `b`, then down the chain in anonymous:15 there is a reference to `b[I]` in the `for (var i = 0; i < 512; i++)` loop, where `b.length === 1`

**Comment by abhisheksoni27** [comment]
@fuzzie360 Fixed!

**Comment by abhisheksoni27** [comment]
@daflair Thanks for that info. I pushed a fix in the morning and forgot to change the matrix size. :laughing: Can you please try again now?

**Comment by daflair** [comment]
I tried to change the matrixSize = 512 and it ran (with chrome devtools open so not optimal for benchmarking)

**Default Mode:**
```
CPU: 0.424s ±6.0%
GPU: 0.075s ±2.5% (5.67 times faster!)
```

**Texture Mode:**
```
CPU: 0.420s ±2.6%
GPU: 0.076s ±3.3% (5.54 times faster!)
```

**Comment by daflair** [comment]
Yup... works... great :)
