### ISSUE TITLE
Kernel only returns power of 2

### ISSUE THREAD

**Issue by Steve73** [gpujs/gpu.js#358]
Calling following kernel on my Windows System (Win 10, NVIDIA GeForce GTX 750, Chrome v68) returns the value 2.

```
const output = gpu.createKernel(function() {
  if (this.thread.x != 1000) return 3;
})
  .setOutput([1])
```

The same kernel returns the value 3 on my Macbook (which is what I expect). If I change the return value in the code of the kernel, the next lower power of two is returned. E.g. if the code return value is 11 the actual return value is 8.

The problem only arises with the if clause. When I remove the if clause the correct value (3) is returned. Also when I use .setFloatOutput(true) the correct value (3) is returned. Any idea what causes this?

**Comment by nickhingston** [comment]
could you run the test suite, see if anything fails there?  might glean some insight!

(clone repository, run `npm install`, `npm run make`, then open ./test/all.html in browser)

**Comment by robertleeplummerjr** [comment]
Was anything found about this?  Possibly reproduced in a jsfiddle?

**Comment by Steve73** [comment]
Sorry for the delay. This jsfiddle

https://jsfiddle.net/argeuLt9/

shows a "3" on my Mac, which is correct.
It shows a "2" on my Windows PC (Win 10, NVIDIA GeForce GTX 750) in Chrome and Firefox. That's wrong.

**Comment by Steve73** [comment]
> (clone repository, run `npm install`, `npm run make`, then open ./test/all.html in browser)

Done:
467 tests completed in 29412 milliseconds, with 5 failed, 0 skipped, and 0 todo.
1847 assertions of 1852 passed, 5 failed.

Following tests failed:

243. OffscreenCanvas used in Worker (1, 0, 1)
Source: | Error: Failed to construct 'Worker': Script at 'file:///C:/Temp/gpu.js-1.10.2/test/features/offscreen-canvas.js' cannot be accessed from origin 'null'.     at Object.<anonymous> (file:///C:/Temp/gpu.js-1.10.2/test/features/offscreen-canvas.js:24:18)

431. Issue #300 nested array index - auto (1, 1, 2)Rerun160 ms
Source: at file:///C:/Temp/gpu.js-1.10.2/test/issues/300-nested-array-index.js:22:8 at file:///C:/Temp/gpu.js-1.10.2/test/issues/300-nested-array-index.js:50:5

432. Issue #300 nested array index - gpu (1, 1, 2)Rerun41 ms
Source: at file:///C:/Temp/gpu.js-1.10.2/test/issues/300-nested-array-index.js:29:8 at file:///C:/Temp/gpu.js-1.10.2/test/issues/300-nested-array-index.js:50:5

433. Issue #300 nested array index - webgl (1, 1, 2)Rerun167 ms
Source: at file:///C:/Temp/gpu.js-1.10.2/test/issues/300-nested-array-index.js:36:8 at file:///C:/Temp/gpu.js-1.10.2/test/issues/300-nested-array-index.js:50:5

434. Issue #300 nested array index - webgl2 (1, 1, 2)Rerun43 ms
Source: at file:///C:/Temp/gpu.js-1.10.2/test/issues/300-nested-array-index.js:43:8 at file:///C:/Temp/gpu.js-1.10.2/test/issues/300-nested-array-index.js:50:5

Does this information help?

**Comment by robertleeplummerjr** [comment]
@Steve73 Can you upgrade to v2, rc2, and let us know if the issue continues?

**Comment by Steve73** [comment]
@robertleeplummerjr Unfortunately, the bug still exists in v2 rc2. For your convenience, here's the fiddle using v2 rc2: https://jsfiddle.net/9ge0szh8/

**Comment by robertleeplummerjr** [comment]
Ty for upgrading and reproducing.  Likely this is an issue with the Intel driver on your OS, which doesn't leave us from handling it like we've done here: https://github.com/gpujs/gpu.js/blob/adf5062427f18e41a6144dd1c8dcc0e099600cb9/src/backend/gl-kernel.js#L31

It may be we just need to introduce a new check for this scenario.

**Comment by robertleeplummerjr** [comment]
Looking at this now.

**Comment by robertleeplummerjr** [comment]
Hum, this may be a windows only bug.  If I disable my nvidia GPU, and run the test, I get the same results.

**Comment by fuzzie360** [comment]
As part of reviving the project, we're closing stale support questions and version-specific reports from older releases. A lot changed today: 2.17.0–2.19.2 shipped and are on npm (`npm install gpu.js`), installs work on modern Node, `new GPU()` works in current browsers, Apple Silicon precision issues are fixed, and CI now guards every change. If this is still relevant on gpu.js@2.19.2, please open a fresh issue with a repro — happy to help. (See #807 for the full status update.)
