### ISSUE TITLE
(Sems broken) - Adding custom functions directly to kernel

### ISSUE THREAD

**Issue by Somebi** [gpujs/gpu.js#447]
It seems this one is broken. Throws "kernel.setFunctions is not a function"

```
kernel.setFunctions(gpu_inner_functions);
       ^

TypeError: kernel.setFunctions is not a function
    at Object.<anonymous> (/var/local/project/matrix_calc.js:22:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)

```

**Comment by Somebi** [comment]
Ubuntu, node.js v10.10.0, using gpu.js version rc.6

**Comment by robertleeplummerjr** [comment]
Use the `GPU` instance for now:
```js
const gpu = new GPU();

gpu.addFunction(gpu_inner_functions);

```

**Comment by Somebi** [comment]
Yea, just reporting. ;)
Testing never is bad, right. ;)

**Comment by robertleeplummerjr** [comment]
I miss-spoke, add them individually.  Testing manual or automated is always welcomed.

**Comment by robertleeplummerjr** [comment]
This should now be resolved in v2 rc9.
