### ISSUE TITLE
Cannot run gpu.js on Google colab  (not supported)

### ISSUE THREAD

**Issue by generic-matrix** [gpujs/gpu.js#530]
## *What* is wrong?
**The gpu.js throws exception "throw new Error(`A requested mode of "${this.mode}" and is not supported`); with both webgl and gpu mode **

## *Where* does it happen?

Google colab --> ijavascript kernel
https://colab.research.google.com/drive/1bpBFzfjZtwFLapRlKKEKZPZy8lz86_ee

## *How* important is this (1-5)?

4

## Error:
```
/content/node_modules/gpu.js/src/gpu.js:177

        throw new Error(`A requested mode of "${this.mode}" and is not supported`);

        ^


Error: A requested mode of "gpu" and is not supported

    at GPU.chooseKernel (/content/node_modules/gpu.js/src/gpu.js:177:15)

    at new GPU (/content/node_modules/gpu.js/src/gpu.js:122:10)

    at evalmachine.<anonymous>:3:11

    at Script.runInThisContext (vm.js:122:20)

    at Object.runInThisContext (vm.js:329:38)

    at run ([eval]:1054:15)

    at onRunRequest ([eval]:888:18)

    at onMessage ([eval]:848:13)

    at process.emit (events.js:198:13)

    at emit (internal/child_process.js:832:12)
```

**Comment by Frontier2018** [comment]
+1
same thing here, I ran the benchmark(https://github.com/gpujs/benchmark) and get the same error

`[root@GPUbackend benchmark]# npm start

> @gpujs/benchmark@3.1.0 start /home/application/benchmark
> node ./index.js

/home/application/benchmark/node_modules/gpu.js/src/gpu.js:187
        throw new Error(`A requested mode of "${this.mode}" and is not supported`);
        ^

Error: A requested mode of "gpu" and is not supported
    at GPU.chooseKernel (/home/application/benchmark/node_modules/gpu.js/src/gpu.js:187:15)
    at new GPU (/home/application/benchmark/node_modules/gpu.js/src/gpu.js:126:10)
    at Object.<anonymous> (/home/application/benchmark/index.js:15:10)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @gpujs/benchmark@3.1.0 start: `node ./index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @gpujs/benchmark@3.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-13T03_29_01_938Z-debug.log`

**Comment by HarshKhandeparkar** [comment]
Hi all! 
For running in node: https://github.com/gpujs/gpu.js#installation & then run `npm rebuild`
For running in colab (I am not sure): You definitely need to have the above packages installed and also need to `npm rebuild`

**Comment by HarshKhandeparkar** [comment]
gpu.js uses a native package to use the GPU via the system graphics driver. Your dev env needs to support such things.

[headless-gl](https://github.com/stackgl/headless-gl) is the package used by gpu.js for its backend, please read their installation steps.

**Comment by fuzzie360** [comment]
As part of reviving the project, we're closing stale support questions and version-specific reports from older releases. A lot changed today: 2.17.0–2.19.2 shipped and are on npm (`npm install gpu.js`), installs work on modern Node, `new GPU()` works in current browsers, Apple Silicon precision issues are fixed, and CI now guards every change. If this is still relevant on gpu.js@2.19.2, please open a fresh issue with a repro — happy to help. (See #807 for the full status update.)
