### ISSUE TITLE
Feature request: tail-recursive functions

### ISSUE THREAD

**Issue by jarble** [gpujs/gpu.js#578]
I'm not sure if GPU.js is able to compile recursive JavaScript functions, but I found [a Babel plugin](https://github.com/krzkaczor/babel-plugin-tailcall-optimization) that converts "tail-recursive" functions to non-recursive functions. Should GPU.js use this plugin to compile recursive functions?

**Comment by robertleeplummerjr** [comment]
Break it, and they will come...


In all seriousness, can you produce something that GPU.js cannot handle?  If so, provide that example and we'll see to it if it can be handled.

**Comment by jarble** [comment]
Here, GPU.js is unable to compile a tail-recursive factorial function:

```
const { GPU } = require('gpu.js');
const gpu = new GPU();

function recursiveFactorial(n, accumulator) {
  if (n <= 0) return accumulator;

  return recursiveFactorial(n-1, n*accumulator);
}

const kernel = gpu.createKernel(function(a) {
  return recursiveFactorial(a[this.thread.x],0);
})
  .setOutput([20])
  .setFunctions([recursiveFactorial]);

const c = kernel([10]);
```

Instead, it produces this error message:

```
C:\Users\jarbl\node_modules\gpu.js\src\backend\function-builder.js:438
            throw new Error('circlical logic detected!');
            ^

Error: circlical logic detected!
    at FunctionBuilder.lookupReturnType (C:\Users\jarbl\node_modules\gpu.js\src\backend\function-builder.js:438:19)
    at WebGLFunctionNode.lookupReturnType (C:\Users\jarbl\node_modules\gpu.js\src\backend\function-builder.js:63:30)
    at WebGLFunctionNode.getType (C:\Users\jarbl\node_modules\gpu.js\src\backend\function-node.js:400:25)
    at WebGLFunctionNode.getType (C:\Users\jarbl\node_modules\gpu.js\src\backend\function-node.js:490:23)
    at WebGLFunctionNode.getType (C:\Users\jarbl\node_modules\gpu.js\src\backend\function-node.js:561:25)
    at FunctionBuilder.lookupReturnType (C:\Users\jarbl\node_modules\gpu.js\src\backend\function-builder.js:447:27)
    at WebGLFunctionNode.lookupReturnType (C:\Users\jarbl\node_modules\gpu.js\src\backend\function-builder.js:63:30)
    at WebGLFunctionNode.getType (C:\Users\jarbl\node_modules\gpu.js\src\backend\function-node.js:400:25)
    at WebGLFunctionNode.getType (C:\Users\jarbl\node_modules\gpu.js\src\backend\function-node.js:490:23)
    at WebGLFunctionNode.getType (C:\Users\jarbl\node_modules\gpu.js\src\backend\function-node.js:561:25)
```

GPU.js would be able to compile tail-recursive functions if it transformed them using [this plugin](https://github.com/krzkaczor/babel-plugin-tailcall-optimization).

**Comment by robertleeplummerjr** [comment]
Is it that big of a deal to just use a loop instead?

**Comment by jarble** [comment]
@robertleeplummerjr . I'm using GPU.js to translate many other tail-recursive functions to GLSL. It would require a lot of effort to refactor all of these functions manually.
