### ISSUE TITLE
Using Jest to test gives console error Not implemented: HTMLCanvasElement.prototype.getContext

### ISSUE THREAD

**Issue by Le5tes** [gpujs/gpu.js#624]
## *What* is wrong?
I am seeing the following console errors when unit testing my Kernals with Jest:
Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package) 
at module.exports (/codebuild/output/src595994766/src/github.com/Le5tes/gravity-simulator/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
102 | at HTMLCanvasElementImpl.getContext (/codebuild/output/src595994766/src/github.com/Le5tes/gravity-simulator/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
103 | at HTMLCanvasElement.getContext (/codebuild/output/src595994766/src/github.com/Le5tes/gravity-simulator/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:102:58)
104 | at Function.setupFeatureChecks (/codebuild/output/src595994766/src/github.com/Le5tes/gravity-simulator/node_modules/gpu.js/src/backend/web-gl2/kernel.js:48:30)
105 | at Function.get isSupported [as isSupported] (/codebuild/output/src595994766/src/github.com/Le5tes/gravity-simulator/node_modules/gpu.js/src/backend/web-gl2/kernel.js:36:10)
106 | at GPU.chooseKernel (/codebuild/output/src595994766/src/github.com/Le5tes/gravity-simulator/node_modules/gpu.js/src/gpu.js:191:28)
107 | at new GPU (/codebuild/output/src595994766/src/github.com/Le5tes/gravity-simulator/node_modules/gpu.js/src/gpu.js:126:10)

Though the code is fine and my tests pass fine.

## *Where* does it happen?
Running tests with Jest. Testing Kernals that do not use canvas.

## *How* important is this (1-5)?
1 - doesn't actually affect me apart from unnecessary error message

## Expected behavior (i.e. solution)
Since I am not requiring the canvas, this error message is not helpful to me. Perhaps this error could be caught and a warning shown instead that the environment doesn't include HTMLCanvasElement.

**Comment by HarshKhandeparkar** [comment]
GPU.js either the HTML `<canvas>` or nodejs dependency `headless-gl` to use the GPU. If you are testing by emulation a browser DOM, there is a very high likelyhood that the canvas element is just a dummy and actually doesn't have the complete implementation.

You'll have to use a complete browser such as puppeteer to test your code.

**Comment by Le5tes** [comment]
But the tests work fine, really I'm just saying that the error message is unnecessary.

**Comment by fuzzie360** [comment]
As part of reviving the project, we're closing stale support questions and version-specific reports from older releases. A lot changed today: 2.17.0–2.19.2 shipped and are on npm (`npm install gpu.js`), installs work on modern Node, `new GPU()` works in current browsers, Apple Silicon precision issues are fixed, and CI now guards every change. If this is still relevant on gpu.js@2.19.2, please open a fresh issue with a repro — happy to help. (See #807 for the full status update.)
