### ISSUE TITLE
Error on running electron app after installing gpu.js

### ISSUE THREAD

**Issue by robosushie** [gpujs/gpu.js#698]
![image](https://user-images.githubusercontent.com/61646255/119928146-a212b000-bf98-11eb-8cd3-61c8bec7c230.png)

Just wanted to share this meme after looking at the crypto market 🤣

## *What* is wrong?
I have built an electron application. After installing gpu.js library 'npm install gpu.js --save'.
When I try to run the the electron application it errors out.
The app is compiled and run using electron-forge library.

I have built an electron application for some signal processing functionality. It receives some data from a device and then processes it and displays the plots.

I have implemented the data receive part using node-addon-api. I am sending the received data from device to js and wanted to implement the signal processing in js using gpujs library.

After installing the gpujs library, when I try to run the app. I am receiving this error.

> \ Preparing native dependencies: 0 / 1webgl.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::shared_ptr<class v8::BackingStore> __cdecl v8::ArrayBuffer::GetBacki
> ngStore(void)" (__imp_?GetBackingStore@ArrayBuffer@v8@@QEAA?AV?$shared_ptr@VBackingStore@v8@@@std@@XZ) referenced in function "public: __cdecl Nan::TypedArrayConten
> ts<char>::TypedArrayContents<char>(class v8::Local<class v8::Value>)" (??0?$TypedArrayContents@D@Nan@@QEAA@V?$Local@VValue@v8@@@v8@@@Z) [E:\Projects\Software_Define 
> d_Radio\boxRF\node_modules\gl\build\webgl.vcxproj]
> E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl\build\Release\webgl.node : fatal error LNK1120: 1 unresolved externals [E:\Projects\Software_Defined_Radio\ 
> boxRF\node_modules\gl\build\webgl.vcxproj]
> × Preparing native dependencies: 0 / 1
> 
> An unhandled error has occurred inside Forge:
> node-gyp failed to rebuild 'E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl'.
> Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
> 
> 
> Error: node-gyp failed to rebuild 'E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl'.
> Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
> 
> 
>     at ModuleRebuilder.rebuildNodeGypModule (E:\Projects\Software_Defined_Radio\boxRF\node_modules\electron-rebuild\src\module-rebuilder.ts:231:13)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at Rebuilder.rebuildModuleAt (E:\Projects\Software_Defined_Radio\boxRF\node_modules\electron-rebuild\src\rebuild.ts:283:5)
>     at Rebuilder.rebuild (E:\Projects\Software_Defined_Radio\boxRF\node_modules\electron-rebuild\src\rebuild.ts:189:9)
>     at E:\Projects\Software_Defined_Radio\boxRF\node_modules\@electron-forge\core\src\util\rebuild.ts:33:5

Below I have also added the entire logs just for reference:

> electron-forge start
> √ Checking your system
> √ Locating Application
> Preparing native dependencies: 0 / 1Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
> / Preparing native dependencies: 0 / 1  Copying E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl/deps/windows/dll/x64/libEGL.dll to E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl\build
>   \Release
> Preparing native dependencies: 0 / 1          1 file(s) copied.
>   Copying E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl/deps/windows/dll/x64/libGLESv2.dll to E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl\bu 
>   ild\Release
>           1 file(s) copied.
>   Copying E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl/deps/windows/dll/x64/d3dcompiler_47.dll to E:\Projects\Software_Defined_Radio\boxRF\node_modules\
>   gl\build\Release
>           1 file(s) copied.
> \ Preparing native dependencies: 0 / 1  bindings.cc
> / Preparing native dependencies: 0 / 1E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl\11.1.0\include\node\v8.h(9182,39): warning C4996: 'v8::MicrotasksCompletedCallback': Use *WithData version.
>  [E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl\build\webgl.vcxproj]
> E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl\11.1.0\include\node\v8.h(9190,42): warning C4996: 'v8::MicrotasksCompletedCallback': Use *WithData version. 
>  [E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl\build\webgl.vcxproj]
> Preparing native dependencies: 0 / 1  webgl.cc
> | Preparing native dependencies: 0 / 1E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl\11.1.0\include\node\v8.h(9182,39): warning C4996: 'v8::MicrotasksCompletedCallback': Use *WithData version.
>  [E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl\build\webgl.vcxproj]
> E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl\11.1.0\include\node\v8.h(9190,42): warning C4996: 'v8::MicrotasksCompletedCallback': Use *WithData version. 
>  [E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl\build\webgl.vcxproj]
> \ Preparing native dependencies: 0 / 1E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl\src\native\webgl.cc(466,37): warning C4312: 'reinterpret_cast': conversion from 'GLint' to 'GLvoid *' of gr
> eater size [E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl\build\webgl.vcxproj]
>  Preparing native dependencies: 0 / 1  procs.cc
> Preparing native dependencies: 0 / 1E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl\11.1.0\include\node\v8.h(9182,39): warning C4996: 'v8::MicrotasksCompletedCallback': Use *WithData version.
>  [E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl\build\webgl.vcxproj]
> E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl\11.1.0\include\node\v8.h(9190,42): warning C4996: 'v8::MicrotasksCompletedCallback': Use *WithData version. 
>  [E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl\build\webgl.vcxproj]
> | Preparing native dependencies: 0 / 1  win_delay_load_hook.cc
> Preparing native dependencies: 0 / 1     Creating library E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl\build\Release\webgl.lib and object E:\Projects\Software_Defined_Radio\boxRF\node_modu
>   les\gl\build\Release\webgl.exp
> \ Preparing native dependencies: 0 / 1webgl.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::shared_ptr<class v8::BackingStore> __cdecl v8::ArrayBuffer::GetBacki
> ngStore(void)" (__imp_?GetBackingStore@ArrayBuffer@v8@@QEAA?AV?$shared_ptr@VBackingStore@v8@@@std@@XZ) referenced in function "public: __cdecl Nan::TypedArrayConten
> ts<char>::TypedArrayContents<char>(class v8::Local<class v8::Value>)" (??0?$TypedArrayContents@D@Nan@@QEAA@V?$Local@VValue@v8@@@v8@@@Z) [E:\Projects\Software_Define 
> d_Radio\boxRF\node_modules\gl\build\webgl.vcxproj]
> E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl\build\Release\webgl.node : fatal error LNK1120: 1 unresolved externals [E:\Projects\Software_Defined_Radio\ 
> boxRF\node_modules\gl\build\webgl.vcxproj]
> × Preparing native dependencies: 0 / 1
> 
> An unhandled error has occurred inside Forge:
> node-gyp failed to rebuild 'E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl'.
> Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
> 
> 
> Error: node-gyp failed to rebuild 'E:\Projects\Software_Defined_Radio\boxRF\node_modules\gl'.
> Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
> 
> 
>     at ModuleRebuilder.rebuildNodeGypModule (E:\Projects\Software_Defined_Radio\boxRF\node_modules\electron-rebuild\src\module-rebuilder.ts:231:13)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at Rebuilder.rebuildModuleAt (E:\Projects\Software_Defined_Radio\boxRF\node_modules\electron-rebuild\src\rebuild.ts:283:5)
>     at Rebuilder.rebuild (E:\Projects\Software_Defined_Radio\boxRF\node_modules\electron-rebuild\src\rebuild.ts:189:9)
>     at E:\Projects\Software_Defined_Radio\boxRF\node_modules\@electron-forge\core\src\util\rebuild.ts:33:5
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! boxrf@1.0.0 start: `electron-forge start`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the boxrf@1.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\susha\AppData\Roaming\npm-cache\_logs\2021-05-28T03_58_03_166Z-debug.log

**Comment by fuzzie360** [comment]
This should be resolved by [2.17.0](https://github.com/gpujs/gpu.js/releases/tag/2.17.0)'s dependency modernization: `gl` is now 8.1.6, which supports current Electron versions (the old 5.x could not build against Electron's headers). Note that in Electron's renderer you can also use gpu.js's browser build without the native `gl` module at all. npm publish is pending; until then: `npm install gpujs/gpu.js#2.18.2`. Please reopen with the rebuild log if your Electron setup still fails.
