### ISSUE TITLE
npm install gpu.js --save-dev fail

### ISSUE THREAD

**Issue by weisiqian** [gpujs/gpu.js#734]
first `npm install gpu.js --save-dev`

then I got this error.

![image](https://user-images.githubusercontent.com/19994951/149607209-b9e609ba-8113-47cf-a084-374bafd08b69.png)

```
PS U:\workspace\bond-data> npm install gpu.js --save-dev
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path U:\workspace\bond-data\node_modules\gl
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@17.3.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.2 found at "C:\Users\Admin\AppData\Local\Programs\Python\Python39\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Community"npm ERR! gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (U:\workspace\bond-data\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at U:\workspace\bond-data\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (U:\workspace\bond-data\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at U:\workspace\bond-data\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at U:\workspace\bond-data\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at U:\workspace\bond-data\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at U:\workspace\bond-data\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:404:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1062:16)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "U:\\workspace\\bond-data\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd U:\workspace\bond-data\node_modules\gl
npm ERR! gyp ERR! node -v v17.3.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Local\npm-cache\_logs\2022-01-15T03_19_20_060Z-debug-0.log
```

my enviroment is :

![image](https://user-images.githubusercontent.com/19994951/149607296-e846659c-6ad3-4e1b-8d61-15b204f15057.png)

![image](https://user-images.githubusercontent.com/19994951/149607383-d88f0da5-1982-4b1b-9a4a-208b54001035.png)

and I have installed visual studio 2022.

![image](https://user-images.githubusercontent.com/19994951/149607335-c976b7b4-0ec4-4e15-9564-a5d907ba246e.png)

**Comment by midnight-dev** [comment]
Could be a node issue rather than gpu.js specific. To me, it looks like node can't find the native tools it expects needed for the install. For best compatibility, install the native build tools that come configured from the node installer. This will probably install an older version of VS Build Tools, like from 2017; it's a light installation and should not conflict with your current 2022 community edition.

You could *probably* just set an environment variable to point to your VC compiler, as mentioned in the error messages, but more work may be needed.

**Comment by sequba** [comment]
I have the same issue. @weisiqian Have you found a solution?

**Comment by fuzzie360** [comment]
Fixed in [2.17.0](https://github.com/gpujs/gpu.js/releases/tag/2.17.0) — the `gl` dependency upgrade to 8.1.6 resolves this class of install failure on current Node/Python toolchains (see #838 for the full story). npm publish is pending; until then: `npm install gpujs/gpu.js#2.18.2`. Please reopen if it still fails for you.
