### ISSUE TITLE
I am running into this issue. 

### ISSUE THREAD

**Issue by devanshsanghvi** [gpujs/gpu.js#813]
Node version : v18.14.0. 
Error: A requested mode of "gpu" and is not supported
    at GPU.chooseKernel (/home/ramanujan/lightweight/node_modules/gpu.js/src/gpu.js:185:15)
    at new GPU (/home/ramanujan/lightweight/node_modules/gpu.js/src/gpu.js:124:10)
    at new RouteState (/home/ramanujan/lightweight/src/gpu/compute_routes.ts:20:16)
    at /home/ramanujan/lightweight/src/gpu/example.ts:14:22
    at Generator.next (<anonymous>)
![Screenshot 2023-02-08 at 5 11 22 PM](https://user-images.githubusercontent.com/29449209/217520171-becf50c1-1b34-4a80-a732-ff254fbaeacc.png)

    at /home/ramanujan/lightweight/src/gpu/example.ts:31:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ramanujan/lightweight/src/gpu/example.ts:27:12)
    at main (/home/ramanujan/lightweight/src/gpu/example.ts:40:12)
    at Object.<anonymous> (/home/ramanujan/lightweight/src/gpu/example.ts:32:1)

**Comment by fuzzie360** [comment]
As part of reviving the project, we're closing stale support questions and version-specific reports from older releases. A lot changed today: 2.17.0–2.19.2 shipped and are on npm (`npm install gpu.js`), installs work on modern Node, `new GPU()` works in current browsers, Apple Silicon precision issues are fixed, and CI now guards every change. If this is still relevant on gpu.js@2.19.2, please open a fresh issue with a repro — happy to help. (See #807 for the full status update.)
