### ISSUE TITLE
error installing npm package

### ISSUE THREAD

**Issue by pablocar80** [gpujs/gpu.js#838]
Error output:

```
npm error code 1
npm error path /home/pablo/gits/inference-ts/node_modules/gl
npm error command failed
npm error command sh -c prebuild-install || node-gyp rebuild
npm error prebuild-install info begin Prebuild-install version 7.1.2
npm error prebuild-install info looking for local prebuild @ prebuilds/gl-v5.0.3-node-v115-linux-x64.tar.gz
npm error prebuild-install info looking for cached prebuild @ /home/pablo/.npm/_prebuilds/eab152-gl-v5.0.3-node-v115-linux-x64.tar.gz
npm error prebuild-install http request GET https://github.com/stackgl/headless-gl/releases/download/v5.0.3/gl-v5.0.3-node-v115-linux-x64.tar.gz
npm error prebuild-install http 404 https://github.com/stackgl/headless-gl/releases/download/v5.0.3/gl-v5.0.3-node-v115-linux-x64.tar.gz
npm error prebuild-install warn install No prebuilt binaries found (target=20.14.0 runtime=node arch=x64 libc= platform=linux)
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@9.4.1
npm error gyp info using node@20.14.0 | linux | x64
npm error gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"
npm error gyp info spawn /usr/bin/python3
npm error gyp info spawn args [
npm error gyp info spawn args   '/home/pablo/gits/inference-ts/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args   'binding.gyp',
npm error gyp info spawn args   '-f',
npm error gyp info spawn args   'make',
npm error gyp info spawn args   '-I',
npm error gyp info spawn args   '/home/pablo/gits/inference-ts/node_modules/gl/build/config.gypi',
npm error gyp info spawn args   '-I',
npm error gyp info spawn args   '/home/pablo/gits/inference-ts/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args   '-I',
npm error gyp info spawn args   '/home/pablo/.cache/node-gyp/20.14.0/include/node/common.gypi',
npm error gyp info spawn args   '-Dlibrary=shared_library',
npm error gyp info spawn args   '-Dvisibility=default',
npm error gyp info spawn args   '-Dnode_root_dir=/home/pablo/.cache/node-gyp/20.14.0',
npm error gyp info spawn args   '-Dnode_gyp_dir=/home/pablo/gits/inference-ts/node_modules/node-gyp',
npm error gyp info spawn args   '-Dnode_lib_file=/home/pablo/.cache/node-gyp/20.14.0/<(target_arch)/node.lib',
npm error gyp info spawn args   '-Dmodule_root_dir=/home/pablo/gits/inference-ts/node_modules/gl',
npm error gyp info spawn args   '-Dnode_engine=v8',
npm error gyp info spawn args   '--depth=.',
npm error gyp info spawn args   '--no-parallel',
npm error gyp info spawn args   '--generator-output',
npm error gyp info spawn args   'build',
npm error gyp info spawn args   '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error /bin/sh: 1: pkg-config: not found
npm error gyp: Call to 'pkg-config --libs-only-L --libs-only-other x11 xi xext' returned exit status 127 while in angle/src/angle.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
npm error gyp ERR! configure error 
npm error gyp ERR! stack Error: `gyp` failed with exit code: 1
npm error gyp ERR! stack     at ChildProcess.onCpExit (/home/pablo/gits/inference-ts/node_modules/node-gyp/lib/configure.js:325:16)
npm error gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
npm error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm error gyp ERR! System Linux 5.15.153.1-microsoft-standard-WSL2
npm error gyp ERR! command "/usr/local/bin/node" "/home/pablo/gits/inference-ts/node_modules/.bin/node-gyp" "rebuild"
npm error gyp ERR! cwd /home/pablo/gits/inference-ts/node_modules/gl
npm error gyp ERR! node -v v20.14.0
npm error gyp ERR! node-gyp -v v9.4.1
npm error gyp ERR! not ok

npm error A complete log of this run can be found in: /home/pablo/.npm/_logs/2024-10-12T17_43_39_793Z-debug-0.log
```

**Comment by pablocar80** [comment]
The command was:

```
npm i gpu.js --add
```

**Comment by pablocar80** [comment]
This was on Linux with WSL. I tried on the same repository on MacOS and I get a very similar message.

**Comment by jamesadcock** [comment]
@pablocar80 I had the same issue using V18 of node worked as a tempoary solution

**Comment by w-oz** [comment]
Same issue

**Comment by razb-viola** [comment]
Same issue. Can't install this.

**Comment by jurian404** [comment]
Same issue on MacOS

**Comment by ilgianlu** [comment]
same problem here.
To work with python 3.12, should update gl lib to 8.1.6 (because of deps in node-gyp 9.4.1, should use ^10.2).
I'm on ubuntu 24.04

**Comment by Fi1osof** [comment]
My dirty workaround: add to package.json 
  "overrides": {
    "gl": "^8.1.6"
  }

**Comment by JenLyndle** [comment]
Thanks [weagle08](https://github.com/weagle08) for pointing me in the right direction through #836 . I was able to update the dependencies as per [weagle08](https://github.com/weagle08)'s fork. The build works with Node v22.14.0. It does not work on 22 due to a bug in vinyl js which gulp depends on - https://github.com/gulpjs/vinyl-fs/issues/350. Node 23 doesn't work due to https://github.com/stackgl/headless-gl/issues/303. Also, the gulp build addon for streamx needed to be changed as per https://github.com/gulpjs/gulp/issues/2802. The PR is https://github.com/gpujs/gpu.js/pull/840. I am using gpu.js in browser and was able to verify that our use case seemed to work as expected with the built dist files. The tests passed fine but am not sure what other functionalities are affected by this update.

**Comment by razb-viola** [comment]
We need this functionality in every node version from so on.

**Comment by AbelVM** [comment]
I'm finding the same error as above 
* node v 22.19.0
* python v 3.13.7
* gpu.js v 2.16.0

```log
npm warn Unknown builtin config "globalignorefile". This will stop working in the next major version of npm.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm warn deprecated npmlog@6.0.2: This package is no longer supported.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm warn deprecated glob@7.2.3: Old versions of glob are not supported, and contain widely publicized security vulnerabilities, which have been fixed in the current version. Please update. Support for old versions may be purchased (at exorbitant rates) by contacting i@izs.me
npm warn deprecated glob@8.1.0: Old versions of glob are not supported, and contain widely publicized security vulnerabilities, which have been fixed in the current version. Please update. Support for old versions may be purchased (at exorbitant rates) by contacting i@izs.me
npm warn deprecated gauge@4.0.4: This package is no longer supported.
npm warn deprecated tar@6.2.1: Old versions of tar are not supported, and contain widely publicized security vulnerabilities, which have been fixed in the current version. Please update. Support for old versions may be purchased (at exorbitant rates) by contacting i@izs.me
npm error code 1
npm error path /data/projects/testing/node_modules/gl
npm error command failed
npm error command sh -c prebuild-install || node-gyp rebuild
npm error prebuild-install warn install No prebuilt binaries found (target=22.19.0 runtime=node arch=x64 libc= platform=linux)
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@9.4.1
npm error gyp info using node@22.19.0 | linux | x64
npm error (node:235913) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
npm error (Use `node --trace-deprecation ...` to show where the warning was created)
npm error gyp info find Python using Python version 3.13.7 found at "/usr/bin/python3"
npm error gyp info spawn /usr/bin/python3
npm error gyp info spawn args [
npm error gyp info spawn args   '/data/projects/testing/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args   'binding.gyp',
npm error gyp info spawn args   '-f',
npm error gyp info spawn args   'make',
npm error gyp info spawn args   '-I',
npm error gyp info spawn args   '/data/projects/testing/node_modules/gl/build/config.gypi',
npm error gyp info spawn args   '-I',
npm error gyp info spawn args   '/data/projects/testing/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args   '-I',
npm error gyp info spawn args   '/home/abel/.cache/node-gyp/22.19.0/include/node/common.gypi',
npm error gyp info spawn args   '-Dlibrary=shared_library',
npm error gyp info spawn args   '-Dvisibility=default',
npm error gyp info spawn args   '-Dnode_root_dir=/home/abel/.cache/node-gyp/22.19.0',
npm error gyp info spawn args   '-Dnode_gyp_dir=/data/projects/testing/node_modules/node-gyp',
npm error gyp info spawn args   '-Dnode_lib_file=/home/abel/.cache/node-gyp/22.19.0/<(target_arch)/node.lib',
npm error gyp info spawn args   '-Dmodule_root_dir=/data/projects/testing/node_modules/gl',
npm error gyp info spawn args   '-Dnode_engine=v8',
npm error gyp info spawn args   '--depth=.',
npm error gyp info spawn args   '--no-parallel',
npm error gyp info spawn args   '--generator-output',
npm error gyp info spawn args   'build',
npm error gyp info spawn args   '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error Package xi was not found in the pkg-config search path.
npm error Perhaps you should add the directory containing `xi.pc'
npm error to the PKG_CONFIG_PATH environment variable
npm error Package 'xi', required by 'virtual:world', not found
npm error gyp: Call to 'pkg-config --libs-only-L --libs-only-other x11 xi xext' returned exit status 1 while in angle/src/angle.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
npm error gyp ERR! configure error 
npm error gyp ERR! stack Error: `gyp` failed with exit code: 1
npm error gyp ERR! stack     at ChildProcess.onCpExit (/data/projects/testing/node_modules/node-gyp/lib/configure.js:325:16)
npm error gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
npm error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm error gyp ERR! System Linux 6.18.7-061807-generic
npm error gyp ERR! command "/usr/local/lib/node_modules/node/bin/node" "/data/projects/testing/node_modules/.bin/node-gyp" "rebuild"
npm error gyp ERR! cwd /data/projects/testing/node_modules/gl
npm error gyp ERR! node -v v22.19.0
npm error gyp ERR! node-gyp -v v9.4.1
npm error gyp ERR! not ok
npm error A complete log of this run can be found in: /home/abel/.npm/_logs/2026-02-10T13_07_02_499Z-debug-0.log  
```

**Comment by AbelVM** [comment]
Once installed XI libraries with ` sudo apt install libxi-dev `, the former error changes and points at `angleutils.h`...

```
npm warn Unknown builtin config "globalignorefile". This will stop working in the next major version of npm.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm warn deprecated npmlog@6.0.2: This package is no longer supported.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm warn deprecated glob@7.2.3: Old versions of glob are not supported, and contain widely publicized security vulnerabilities, which have been fixed in the current version. Please update. Support for old versions may be purchased (at exorbitant rates) by contacting i@izs.me
npm warn deprecated glob@8.1.0: Old versions of glob are not supported, and contain widely publicized security vulnerabilities, which have been fixed in the current version. Please update. Support for old versions may be purchased (at exorbitant rates) by contacting i@izs.me
npm warn deprecated gauge@4.0.4: This package is no longer supported.
npm warn deprecated tar@6.2.1: Old versions of tar are not supported, and contain widely publicized security vulnerabilities, which have been fixed in the current version. Please update. Support for old versions may be purchased (at exorbitant rates) by contacting i@izs.me
npm error code 1
npm error path /data/projects/multiband2vector/node_modules/gl
npm error command failed
npm error command sh -c prebuild-install || node-gyp rebuild
npm error make: Entering directory '/data/projects/multiband2vector/node_modules/gl/build'
npm error   CXX(target) Release/obj.target/angle_common/angle/src/common/Float16ToFloat32.o
npm error make: Leaving directory '/data/projects/multiband2vector/node_modules/gl/build'
npm error prebuild-install warn install No prebuilt binaries found (target=22.19.0 runtime=node arch=x64 libc= platform=linux)
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@9.4.1
npm error gyp info using node@22.19.0 | linux | x64
npm error (node:12716) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
npm error (Use `node --trace-deprecation ...` to show where the warning was created)
npm error gyp info find Python using Python version 3.13.7 found at "/usr/bin/python3"
npm error gyp info spawn /usr/bin/python3
npm error gyp info spawn args [
npm error gyp info spawn args   '/data/projects/multiband2vector/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args   'binding.gyp',
npm error gyp info spawn args   '-f',
npm error gyp info spawn args   'make',
npm error gyp info spawn args   '-I',
npm error gyp info spawn args   '/data/projects/multiband2vector/node_modules/gl/build/config.gypi',
npm error gyp info spawn args   '-I',
npm error gyp info spawn args   '/data/projects/multiband2vector/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args   '-I',
npm error gyp info spawn args   '/home/abel/.cache/node-gyp/22.19.0/include/node/common.gypi',
npm error gyp info spawn args   '-Dlibrary=shared_library',
npm error gyp info spawn args   '-Dvisibility=default',
npm error gyp info spawn args   '-Dnode_root_dir=/home/abel/.cache/node-gyp/22.19.0',
npm error gyp info spawn args   '-Dnode_gyp_dir=/data/projects/multiband2vector/node_modules/node-gyp',
npm error gyp info spawn args   '-Dnode_lib_file=/home/abel/.cache/node-gyp/22.19.0/<(target_arch)/node.lib',
npm error gyp info spawn args   '-Dmodule_root_dir=/data/projects/multiband2vector/node_modules/gl',
npm error gyp info spawn args   '-Dnode_engine=v8',
npm error gyp info spawn args   '--depth=.',
npm error gyp info spawn args   '--no-parallel',
npm error gyp info spawn args   '--generator-output',
npm error gyp info spawn args   'build',
npm error gyp info spawn args   '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp info spawn make
npm error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm error In file included from ../angle/src/common/debug.h:16,
npm error                  from ../angle/src/common/mathutil.h:12,
npm error                  from ../angle/src/common/Float16ToFloat32.cpp:9:
npm error ../angle/src/common/angleutils.h:36:14: error: ‘uintptr_t’ does not name a type
npm error    36 | extern const uintptr_t DirtyPointer;
npm error       |              ^~~~~~~~~
npm error ../angle/src/common/angleutils.h:21:1: note: ‘uintptr_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
npm error    20 | #include <vector>
npm error   +++ |+#include <cstdint>
npm error    21 | 
npm error make: *** [angle/src/angle_common.target.mk:156: Release/obj.target/angle_common/angle/src/common/Float16ToFloat32.o] Error 1
npm error gyp ERR! build error 
npm error gyp ERR! stack Error: `make` failed with exit code: 2
npm error gyp ERR! stack     at ChildProcess.onExit (/data/projects/multiband2vector/node_modules/node-gyp/lib/build.js:203:23)
npm error gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
npm error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm error gyp ERR! System Linux 6.18.7-061807-generic
npm error gyp ERR! command "/usr/local/lib/node_modules/node/bin/node" "/data/projects/multiband2vector/node_modules/.bin/node-gyp" "rebuild"
npm error gyp ERR! cwd /data/projects/multiband2vector/node_modules/gl
npm error gyp ERR! node -v v22.19.0
npm error gyp ERR! node-gyp -v v9.4.1
npm error gyp ERR! not ok
npm error A complete log of this run can be found in: /home/abel/.npm/_logs/2026-02-10T13_36_09_434Z-debug-0.log  
```

**Comment by AbelVM** [comment]
Ok, fixed by:
* Installing some missing packages `sudo apt install libxi-dev gcc-11 g++-11`
* Adding some overrides to `packages.json`
```javascript
  "overrides": {
    "gpu.js": {
      "gl": {
        "node-gyp": ">7.0.0"
      }
    }
  }
```
* Installing with GCC11: `CC=gcc-11 CXX=g++-11 npm install gpu.js`

**Comment by fuzzie360** [comment]
Fixed in [2.17.0](https://github.com/gpujs/gpu.js/releases/tag/2.17.0). The `gl` (headless-gl) dependency was upgraded 5.x → 8.1.6 (along with the rest of the dependency chain) via #840 — huge thanks to @JenLyndle and @weagle08. `gl` 8.1.6 ships prebuilt binaries for current Node versions and builds cleanly against Python 3.12+, so the `node-gyp`/`pkg-config xi` failures in this thread no longer occur.

Verified with a clean `npm ci` on Node 22 on both macOS (arm64) and Linux (x64/arm64 — note arm64 Linux has no prebuilds, so it needs the usual headless-gl build deps: `build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config`).

The npm publish of 2.17.0 is pending (maintainer access is being sorted out). Until it lands you can install straight from the release tag:

```bash
npm install gpujs/gpu.js#2.17.0
```

The `overrides: { "gl": "^8.1.6" }` workaround mentioned above is no longer needed.
